### ISSUE TITLE
VCS polling is completely broken on v1.3.0 (every workspace errors every cycle)

### ISSUE THREAD

**Issue by mattrobinsonsre** [mattrobinsonsre/terrapod#1244]
## Summary

On v1.3.0, **every VCS-connected workspace fails every poll cycle**. VCS polling is
completely dead: no branch pushes are detected, no speculative PR/MR plans are created,
and every workspace shows a VCS error.

```
AttributeError: 'list' object has no attribute 'get_or_fetch'
  event: "Error polling workspace VCS"
  logger: terrapod.services.vcs_poller
```

## Root cause

A transposed positional argument, introduced in #1097 (the per-cycle VCS metadata
deduplication).

Both `_poll_workspace_branch` and `_poll_workspace_prs` end with:

```python
cache: VCSArchiveCache | None = None,
meta: VCSMetadataCache | None = None,
fetch_paths: list[str] | None = None,
```

but `_poll_workspace` called them as:

```python
await _poll_workspace_branch(db, ws, conn, owner, repo, branch, cache, fetch_paths, meta)
```

`fetch_paths` (a `list`) binds to `meta`, and the `VCSMetadataCache` binds to
`fetch_paths`. The helpers then take the `meta is not None` branch and call
`meta.get_or_fetch(...)` on a list.

The exception is caught by the per-workspace error handler, so it presents as a VCS
error on every workspace rather than a crash.

## Why no test caught it

The gap is precise. Every existing `_poll_workspace` test omits `meta`, so it takes the
`meta is None` short-circuit inside the helpers and never reaches the transposed call.
The tests that *do* construct a `VCSMetadataCache` call the inner helpers directly,
bypassing `_poll_workspace` entirely.

**Production is the only caller that passes both `meta` and `fetch_paths`** — the one
combination nothing exercised.

## Fix

Pass the tail arguments by keyword at both call sites, plus two regression tests that
drive `_poll_workspace` with both `meta` and `fetch_paths` set: one behavioural (mocking
only at the provider boundary, asserting no error is recorded) and one that pins the
argument binding itself.

## Impact

Any v1.3.0 install using VCS-connected workspaces. Agent/CLI-driven runs are unaffected.
Fixed in v1.3.1.
